[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Single Page App fallback so client routes work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
